Update install

diff --git a/scripts/install b/scripts/install
--- a/scripts/install
+++ b/scripts/install
@@ -1,6 +1,58 @@
 #!/bin/bash
 
+#=================================================
+# GENERIC STARTING
+#=================================================
+# IMPORT GENERIC HELPERS
+#=================================================
 
+source .fonctions
+source /usr/share/yunohost/helpers
+
+#=================================================
+# MANAGE FAILURE OF THE SCRIPT
+#=================================================
+
+ynh_check_error	# Active trap pour arrêter le script si une erreur est détectée.
+
+#=================================================
+# RETRIEVE ARGUMENTS FROM THE MANIFEST
+#=================================================
+
+domain=$YNH_APP_ARG_DOMAIN
+path_url=$YNH_APP_ARG_PATH
+is_public=$YNH_APP_ARG_IS_PUBLIC
+admin_name=$YNH_APP_ARG_ADMIN_NAME
+admin_pass=$YNH_APP_ARG_ADMIN_PASS
+admin_email=$YNH_APP_ARG_ADMIN_EMAIL
+
+app=$YNH_APP_INSTANCE_NAME
+
+#=================================================
+# CHECK IF THE APP CAN BE INSTALLED WITH THIS ARGS
+#=================================================
+
+CHECK_USER "$admin_name"	# Vérifie la validité de l'user admin
+path_url=$(ynh_normalize_url_path $path_url)	# Vérifie et corrige la syntaxe du path.
+CHECK_DOMAINPATH	# Vérifie la disponibilité du path et du domaine.
+CHECK_FINALPATH	# Vérifie que le dossier de destination n'est pas déjà utilisé.
+
+#=================================================
+# STORE SETTINGS FROM MANIFEST
+#=================================================
+
+user="$app"
+ynh_app_setting_set "$app" is_public "$is_public"
+ynh_app_setting_set "$app" admin_pass "$admin_pass"
+ynh_app_setting_set "$app" admin_name "$admin_name"
+ynh_app_setting_set "$app" admin_email "$admin_email"
+
+#=================================================
+# Check password strength
+#=================================================
+
+[[ ${#admin_pass} -gt 5 ]] || ynh_die \
+"The password is too weak, it must be longer than 5 characters"
 
 
 
@@ -20,8 +72,10 @@ sudo apt-get install -y build-essential linux-headers-`uname -r` openssh-server 
   
   sudo pear install Console_Getopt
   
-  
+#=================================================  
 #  Install iksemel
+#=================================================
+
 cd /usr/src
 wget https://iksemel.googlecode.com/files/iksemel-1.4.tar.gz
 tar xf iksemel-1.4.tar.gz
@@ -31,7 +85,9 @@ make
 make install
 ldconfig
 
+#=================================================
 # Installation of asterisk
+#=================================================
 
 cd /usr/src
 wget http://downloads.asterisk.org/pub/telephony/dahdi-linux-complete/dahdi-linux-complete-current.tar.gz
@@ -40,7 +96,10 @@ wget http://downloads.asterisk.org/pub/telephony/asterisk/asterisk-13-current.ta
 wget -O jansson.tar.gz https://github.com/akheron/jansson/archive/v2.7.tar.gz
 wget http://www.pjsip.org/release/2.4/pjproject-2.4.tar.bz2
 
+#=================================================
 # Installation of DAHDI 
+#=================================================
+
 cd /usr/src
 tar xvfz dahdi-linux-complete-current.tar.gz
 rm -f dahdi-linux-complete-current.tar.gz
@@ -55,7 +114,10 @@ cd libpri-*
 make
 make install
 
+#=================================================
 # Compile and install pjproject
+#=================================================
+
 cd /usr/src
 tar -xjvf pjproject-2.4.tar.bz2
 rm -f pjproject-2.4.tar.bz2
@@ -74,7 +136,10 @@ autoreconf -i
 make
 make install
 
+#=================================================
 # Compile and install Asterisk
+#=================================================
+
 cd /usr/src
 tar xvfz asterisk-13-current.tar.gz
 rm -f asterisk-13-current.tar.gz
@@ -88,7 +153,10 @@ make config
 ldconfig
 update-rc.d -f asterisk remove
 
+#=================================================
 # Installation of Soundfile of Asterisk
+#=================================================
+
 cd /var/lib/asterisk/sounds
 wget http://downloads.asterisk.org/pub/telephony/sounds/asterisk-core-sounds-en-wav-current.tar.gz
 wget http://downloads.asterisk.org/pub/telephony/sounds/asterisk-extra-sounds-en-wav-current.tar.gz
@@ -104,13 +172,15 @@ rm -f asterisk-extra-sounds-en-g722-current.tar.gz
 tar xfz asterisk-core-sounds-en-g722-current.tar.gz
 rm -f asterisk-core-sounds-en-g722-current.tar.gz
 
+#=================================================
 # Installation of FreePBX
+#=================================================
 useradd -m asterisk
 chown asterisk. /var/run/asterisk
 chown -R asterisk. /etc/asterisk
 chown -R asterisk. /var/{lib,log,spool}/asterisk
 chown -R asterisk. /usr/lib/asterisk
-rm -rf /var/www/html
+
 
 if [ 'uname -r' = x86_64 ] then
 cat >> /etc/odbcinst.ini << EOF
